[DPE-2345][DPE-2451] restore action
canonical/opensearch-operator pull request #137
Opened 2023-10-16 20:02 UTC by phvalguima

Extends https://github.com/canonical/opensearch-operator/pull/135 and adds restore support.

This PR will roll the cluster's indices back to the snapshot and override any conflicting index.

It tests two scenarios:
1) Snapshot / restore in the same cluster
2) Snapshot / redeploy cluster / restore

2023-11-20 13:31 UTC, Mehdi-Bendriss reviewed
Will review this PR once feedback is addressed on the create / list backups PR. As they're closely intertwined.

2023-12-13 18:49 UTC, phvalguima commented
Following up https://github.com/canonical/opensearch-operator/pull/135 and addressing @delgod last few comments there:
* plugin_opensearch_knn: why switching from false to true
* to have a similar interface with postgresql charm and change the `_fetch_snapshot` naming convention
* remove restrictions of backup / restore only on leader unit
* to discover the HTTP/HTTPS protocol from the `endpoint` provided
* `region` should not be mandatory in the charm
* get the `storage_class` information from s3-integrator and configure it, if available
* Change:
```
-                BlockedStatus(f"Disabling backup not possible: {snapshot_status}")
+                MaintanceStatus(f"Disabling backup postponed till backup in progress: {snapshot_status}")
```

2023-12-14 08:01 UTC, delgod requested changes

2023-12-14 08:01 UTC, delgod commented on lib/charms/opensearch/v0/opensearch_backups.py
>              event.fail("Failed: backup service is not configured yet")
still UX should be improved. e.g. id should be a time of backup start, it should be a table with in-progress/failed/successfull status, etc
```
$ juju run postgresql/3 list-backups
...
backups: |-
  backup-id             | backup-type  | backup-status
  ----------------------------------------------------
  2023-10-19T11:36:23Z  | physical     | finished
```

2023-12-14 09:15 UTC, juditnovak approved these changes
LGTM (on my VERY limited level of understanding)

2023-12-14 12:00 UTC, juditnovak approved these changes
LGTM

2023-12-14 12:10 UTC, merged