Use `relation_created` instead of `relation_joined`
canonical/opensearch-operator pull request #201
Opened 2024-03-15 14:58 UTC by carlcsaposs-canonical

The handler is supposed to run when the relation is created, not when a unit joins the relation

See https://github.com/canonical/mysql-router-k8s-operator/pull/101

2024-03-15 16:08 UTC, juditnovak reviewed
I get the rationale, indeed makes more sense to request certificates on `relation-joined`.

Out of curiousity: was there any issue with the previous workflows? I.e. is this a fix or rather preventive to correct our incorrect worklows?

Either way, we sould have the tests passing ;-)

2024-03-15 16:11 UTC, Mehdi-Bendriss commented
Hmm, I don't think that's accurate. In OpenSearch, **every** opensearch unit must get its own certificates. And this will not be possible with `RelationCreatedEvent` which would have already been invoked initially - RelationJoinedEvent will guarantee that every unit requests its own certificates. Did i misunderstand something?

2024-03-16 12:31 UTC, phvalguima requested changes

2024-03-16 12:31 UTC, phvalguima commented on lib/charms/opensearch/v0/opensearch_tls.py
> -from ops.charm import ActionEvent, RelationBrokenEvent, RelationJoinedEvent
Hi @carlcsaposs-canonical thanks for this.

I reviewed TLS lib docstring (most recent one), and I noticed two things:
1) They are also recommending to use `relation-joined`: we need a bug there asking to update the docs in this case
2) I also noticed they have more events that we should track in opensearch - the [invalidated events](https://github.com/canonical/self-signed-certificates-operator/blob/7f41b9f22feecf55f556c8e80ea7e6a26e646321/lib/charms/tls_certificates_interface/v3/tls_certificates.py#L159-L165)

For (2), I've filed a separate bug here: #204.

2024-03-18 07:03 UTC, Mehdi-Bendriss approved these changes

2024-03-29 15:45 UTC, phvalguima submitted a review, later dismissed

2024-04-16 06:55 UTC, phvalguima submitted a review, later dismissed

2024-04-16 12:43 UTC, Mehdi-Bendriss approved these changes

2024-04-17 14:15 UTC, Mehdi-Bendriss approved these changes

2024-04-18 10:53 UTC, merged