Pin lxd to 5.20 in integration tests
canonical/opensearch-operator pull request #228
Opened 2024-04-12 07:15 UTC by carlcsaposs-canonical

Workaround for https://github.com/canonical/opensearch-operator/issues/227

2024-04-12 07:32 UTC, Mehdi-Bendriss approved these changes
Thank you!

2024-04-12 10:48 UTC, phvalguima requested changes

2024-04-12 10:48 UTC, phvalguima commented on .github/workflows/ci.yaml
> +      lxd-snap-channel: 5.20/stable
@carlcsaposs-canonical this is unnecessary. Check my comment on #227: (1) I fixed the last `limits.network.priority` command and (2) we need to figure out another way to implement this network cut.

2024-04-16 06:53 UTC, phvalguima commented on .github/workflows/ci.yaml
> +      lxd-snap-channel: 5.20/stable
@carlcsaposs-canonical @Mehdi-Bendriss we don't need to pin, check here: https://github.com/canonical/opensearch-operator/pull/239

And this is a permanent fix moving forward with 5.21+

2024-04-16 07:09 UTC, closed without merging