[DPE-4206] _rel_err_data always return True for main orchestrator
canonical/opensearch-operator pull request #257
Opened 2024-04-24 15:43 UTC by phvalguima

More details is present on issue #256.

Closes #256.

2024-04-24 16:42 UTC, Mehdi-Bendriss requested changes

2024-04-24 16:42 UTC, Mehdi-Bendriss commented on lib/charms/opensearch/v0/opensearch_relation_peer_cluster.py
> +        elif orchestrators.failover_app and orchestrators.failover_app == self.charm.app.name:
I believe what we had was correct, though incomplete. Perhaps: 
```suggestion
        elif orchestrators.main_app != self.charm.app.name and orchestrator.failover_app and orchestrators.failover_app != self.charm.app.name:
```

2024-04-25 08:17 UTC, Mehdi-Bendriss approved these changes

2024-04-25 08:32 UTC, juditnovak approved these changes
I really count on Large Deployment experts knowledge here. As for an "outsider", looks good.

2024-04-25 08:35 UTC, merged