[DPE-5599][Juju 3.6] Break PR/worflow & nightly tests + DPW update
canonical/opensearch-operator pull request #467
Opened 2024-10-02 12:03 UTC by phvalguima

Updates the data platform workflow to the latest version: 22.0.0.

Breaks the ci.yaml file into workflow.yaml, for PRs and workflows; and nightly.yaml for the CI runs at night. The nightly.yaml is updated to Juju 3.6.

2024-10-02 12:13 UTC, phvalguima commented on .github/workflows/release.yaml
> -  # release-libraries:
check libs already done on workflow.yaml

2024-10-03 08:09 UTC, carlcsaposs-canonical submitted a review, later dismissed
looks good!

PR description appears to be outdated

> Breaks the ci.yaml file into workflow.yaml, for PRs and workflows; and nightly.yaml for the CI runs at night.

I would not recommend that approach—the approach currently in the PR is recommended instead

2024-10-03 10:18 UTC, carlcsaposs-canonical submitted a review, later dismissed

2024-10-03 10:26 UTC, phvalguima commented
We should stay with pinned juju agent + a renovate config to bump this version, as described here: https://github.com/canonical/opensearch-operator/issues/470

2024-10-03 10:38 UTC, carlcsaposs-canonical requested changes
remember to remove build wrapper from tox.ini

full migration instructions: https://github.com/canonical/data-platform-workflows/releases/tag/v22.0.0

2024-10-03 10:38 UTC, carlcsaposs-canonical commented on charmcraft.yaml
> +      craftctl default
```suggestion

      craftctl default
```
nit for consistency with other charms

2024-10-03 10:39 UTC, carlcsaposs-canonical commented
also please update dpw in pyproject.toml—compatibility only guaranteed if every dpw is on the same version

(fyi, the renovate preset can take care of this for you)

2024-10-03 14:15 UTC, carlcsaposs-canonical submitted a review, later dismissed

2024-10-03 14:15 UTC, carlcsaposs-canonical commented on poetry.lock
fyi it looks like a lot of deps were updated

if that's not your intention, you can revert poetry.lock (git checkout origin/main -- poetry.lock) and run `poetry lock --no-update` to get minimal changes to make lock valid for pyproject.toml

2024-10-03 19:07 UTC, phvalguima commented on poetry.lock
It was the intention actually

2024-10-04 12:40 UTC, carlcsaposs-canonical submitted a review, later dismissed

2024-10-04 12:40 UTC, carlcsaposs-canonical commented on pyproject.toml
> +ops = "<2.17"
might want to include a lower pin so that a new dep doesn't lower it (e.g. to ops 1.0 or 2.3 or something) silently

also might be worth including comment to explain why upper pin exists and/or creating ticket to remove

2024-10-05 16:13 UTC, Mehdi-Bendriss approved these changes, later dismissed

2024-10-07 15:14 UTC, MiaAltieri commented on .github/workflows/release.yaml
> -  # release-libraries:
should this be commented back in ?

2024-10-07 15:19 UTC, MiaAltieri approved these changes

2024-10-07 15:20 UTC, juditnovak approved these changes
LGTM

2024-10-07 15:21 UTC, merged