[DPE-5615] - Manage chain file for requests like that of a CA
canonical/opensearch-operator pull request #472
Opened 2024-10-11 06:03 UTC by skourta

## Issue
We were not updating the `chain.pem` file used by the request module to send requests which caused communication cuts in a lot of cases.

## Solution
Add the new chain to the `chain.pem` on CA rotation initiated and only delete it if all the nodes are done updating their CA **and** certs.

## Summary of changes
This pull request introduces several changes to improve the handling of CA (Certificate Authority) rotation in the OpenSearch charm. The key changes include enhancements to the CA rotation process, ensuring proper cleanup of old CA certificates, and updating the request CA bundle. Additionally, a new method has been added to handle the completion of CA rotation.

### Enhancements to CA Rotation Process:

* [`lib/charms/opensearch/v0/opensearch_base_charm.py`](diffhunk://#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43R645-R652): Added checks to ensure that old CA certificates are only removed after the CA rotation is complete in the cluster. This includes new conditions in methods like `_on_update_status`, `on_tls_conf_set`, `_post_start_init`, and `_start_opensearch`. [[1]](diffhunk://#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43R645-R652) [[2]](diffhunk://#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43L821-R839) [[3]](diffhunk://#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43L952-L957) [[4]](diffhunk://#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43L992-L996) [[5]](diffhunk://#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43L1164-L1167) [[6]](diffhunk://#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43R1180-R1188)

### Improvements to TLS Management:

* [`lib/charms/opensearch/v0/opensearch_tls.py`](diffhunk://#diff-fcbdb57c37f5d32b5ecf046327cfa9ee91a33f156714ea7fb6f000a48d2c4ca4R880-R911): Introduced a new method `ca_and_certs_rotation_complete_in_cluster` to check the completion of CA and certificate rotation across all units.
* Added methods `_add_ca_to_request_bundle` and `_remove_ca_from_request_bundle` to manage CA certificates in the request bundle. [[1]](diffhunk://#diff-fcbdb57c37f5d32b5ecf046327cfa9ee91a33f156714ea7fb6f000a48d2c4ca4R560-R561) [[2]](diffhunk://#diff-fcbdb57c37f5d32b5ecf046327cfa9ee91a33f156714ea7fb6f000a48d2c4ca4R614-R615) [[3]](diffhunk://#diff-fcbdb57c37f5d32b5ecf046327cfa9ee91a33f156714ea7fb6f000a48d2c4ca4R625-R626) [[4]](diffhunk://#diff-fcbdb57c37f5d32b5ecf046327cfa9ee91a33f156714ea7fb6f000a48d2c4ca4L887-R957)

### General Updates:

* Updated the `LIBPATCH` version in `opensearch_base_charm.py` and `opensearch_tls.py` to reflect the new changes. [[1]](diffhunk://#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43L121-R121) [[2]](diffhunk://#diff-fcbdb57c37f5d32b5ecf046327cfa9ee91a33f156714ea7fb6f000a48d2c4ca4L64-R65)
* Imported `Path` from `pathlib` in `opensearch_tls.py` to handle file paths more effectively.

2024-10-14 13:20 UTC, reneradoi requested changes
Hey @skourta thank you for these changes! The concept is clear and makes sense, I've only found a few details that need to be fixed before moving on with it.

2024-10-14 13:20 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_base_charm.py
> +LIBPATCH = 3
I think an update of this version is not required here.

2024-10-14 13:20 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_tls.py
> +LIBPATCH = 2
I think an update of this version is not required here.

2024-10-14 13:20 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_tls.py
> +                            f"TLS CA rotation not complete for unit {unit}: {relation} | tls_ca_renewing: {relation.data[unit].get('tls_ca_renewing')} | tls_ca_renewed: {relation.data[unit].get('tls_
Maybe break this into a multi-line string for better readability.

2024-10-14 13:20 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_tls.py
> +            "tls_ca_renewed" or self.charm.peers_data.get(Scope.UNIT, "tls_configured") != "True",
I think the syntax here is not correct. Shouldn't it be: `... or self.charm.peers_data.get(Scope.UNIT, "tls_ca_renewed") or ...` instead?

2024-10-14 13:20 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_base_charm.py
> +            self.tls._read_stored_ca("old-ca")
If we use this method outside of `opensearch_tls.py` we should rename it (remove the underscore) to make the "public" use explicit.

2024-10-15 08:04 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_base_charm.py
> +            self.tls.on_ca_certs_rotation_complete()
I've specifically tested this manually on my local machine, and unfortunately it failed.

This is the setup:
- deploy 3 nodes of Opensearch, run the usual CA rotation via triggering a config change
- waiting for the CA rotation to complete, then remove two units and only keep one of those that did not finish last on the first CA rotation (to enforce the `old-ca` to still be there)
- wait for one (or several) `update-status` to pass
- trigger another CA rotation on that one node

This fails then with `Destination alias <old-ca> already exists` on `CertificateAvailableEvent`. That means the `old-ca` was not removed on the `update_status` runs. I am still trying to figure out why, didn't find the root cause yet.

2024-10-15 10:34 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_tls.py
> +                        or relation.data[unit].get("tls_configured") != "True"
This is basically the same condition as in line 891 and should be adjusted to `is not True` as well.

2024-10-15 10:40 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_tls.py
> +                        or relation.data[unit].get("tls_configured") != "True"
Nevermind, was wrong from my side.

2024-10-15 16:15 UTC, reneradoi commented on lib/charms/opensearch/v0/opensearch_base_charm.py
> +            self.tls.on_ca_certs_rotation_complete()
After rotating the CA and applying the new certs, the `old-ca` is now removed correctly.

2024-10-15 16:18 UTC, reneradoi reviewed
For documentation purposes, result of manual testing:

The units are not performing the rolling restart in correct fashion anymore.
```
opensearch-0.427 -- (10.120.198.4) -- \[idle (since: 12:42:24)\] maintenance: Waiting for TLS to be fully configured...
opensearch-1.427\* -- (10.120.198.172) -- \[idle (since: 12:42:23)\] maintenance: Applying new CA certificate...
opensearch-2.427 -- (10.120.198.60) -- \[executing (since: 12:42:18)\] waiting: Waiting for OpenSearch to start...

opensearch-0.427 -- (10.120.198.4) -- \[idle (since: 12:49:44)\] maintenance: Waiting for TLS to be fully configured...
opensearch-1.427\* -- (10.120.198.172) -- \[executing (since: 12:49:43)\] waiting: The OpenSearch service is stopping.
opensearch-2.427 -- (10.120.198.60) -- \[idle (since: 12:49:44)\] waiting: Waiting for OpenSearch to start...
```
Even though unit 2 is not started yet, unit 1 starts applying the certs.

Another behaviour I've noticed (separate test run):
- unit 2 applies new CA
- unit 0 applies new CA
- unit 2 applies new certs, even though unit 1 did not apply new CA yet.

2024-10-16 07:10 UTC, skourta commented
> For documentation purposes, result of manual testing:
> 
> The units are not performing the rolling restart in correct fashion anymore.
> 
> ```
> opensearch-0.427 -- (10.120.198.4) -- \[idle (since: 12:42:24)\] maintenance: Waiting for TLS to be fully configured...
> opensearch-1.427\* -- (10.120.198.172) -- \[idle (since: 12:42:23)\] maintenance: Applying new CA certificate...
> opensearch-2.427 -- (10.120.198.60) -- \[executing (since: 12:42:18)\] waiting: Waiting for OpenSearch to start...
> 
> opensearch-0.427 -- (10.120.198.4) -- \[idle (since: 12:49:44)\] maintenance: Waiting for TLS to be fully configured...
> opensearch-1.427\* -- (10.120.198.172) -- \[executing (since: 12:49:43)\] waiting: The OpenSearch service is stopping.
> opensearch-2.427 -- (10.120.198.60) -- \[idle (since: 12:49:44)\] waiting: Waiting for OpenSearch to start...
> ```
> 
> Even though unit 2 is not started yet, unit 1 starts applying the certs.
> 
> Another behaviour I've noticed (separate test run):
> 
> * unit 2 applies new CA
> * unit 0 applies new CA
> * unit 2 applies new certs, even though unit 1 did not apply new CA yet.

This is not related to this PR. I tested and it is happening in `2/edge` as well. As I mentioned on Mattermost yesterday this seems to be coming from the unit getting an outdated state of the peer relation data bag.

2024-10-16 08:10 UTC, reneradoi commented
@skourta A couple of more test runs on my dev machine were successfull now. I agree with your assumption, let's move on with this.

2024-10-16 08:11 UTC, reneradoi approved these changes
All comments and required changes have been addressed.

2024-10-16 10:00 UTC, phvalguima approved these changes

2024-10-16 20:37 UTC, Mehdi-Bendriss approved these changes

2024-10-17 04:26 UTC, merged