Add CI and unit tests for prometheus rules using promtool
canonical/opensearch-operator pull request #505
Opened 2024-11-14 22:39 UTC by gabrielcocenza

- It's good to have unit tests for the prometheus alerts and also check if the prometheus_alerts.yaml is a valid file.

- using promtool is possible to check the rules and also run unit tests.

## How to test this PR

1. Install the prometheus snap:
```shell
sudo snap install prometheus
```

2. Run to check if the rules file is valid:
```shell
promtool check rules src/alert_rules/prometheus/*.yaml
```

3. Run the unit tests:
```
promtool test rules tests/unit/test_alert_rules/*.yaml
```

2024-12-11 14:06 UTC, phvalguima commented on .github/workflows/test_prometheus_rules.yaml
> +    runs-on: ubuntu-latest
Is it possible to move to self-hosted CI?

2024-12-11 14:39 UTC, gabrielcocenza commented on .github/workflows/test_prometheus_rules.yaml
> +    runs-on: ubuntu-latest
I think it is. Is there a specific reason to change to self-hosted?

2024-12-12 16:09 UTC, zmraul requested changes
See [comment on opensearch-dashboards](https://github.com/canonical/opensearch-dashboards-operator/pull/142#pullrequestreview-2500122619)

2024-12-18 09:57 UTC, phvalguima commented on .github/workflows/test_prometheus_rules.yaml
> +    runs-on: ubuntu-latest
Not really, just more runners. But as you removed from the pull request path, as @zmraul suggested, I am fine keeping it here.

2024-12-18 09:58 UTC, phvalguima approved these changes

2024-12-18 16:31 UTC, zmraul approved these changes

2024-12-18 17:08 UTC, merged