Fix rejection ratio alert
canonical/opensearch-operator pull request #508
Opened 2024-11-27 20:14 UTC by gabrielcocenza

OpenSearch does not have thread pool with the name bulk. However, there is a field named "write" that can be used by bulk or writing a single instance.

This PR adds the necessary logic to use the OpenSearch data coming from the exporter and because the expression is big, it was separated into smaller expressions using record.

To see the original rule that was inspiration for this alert see this [repo](https://github.com/lukas-vlcek/prometheus-elasticsearch-rules/blob/master/logging_elasticsearch.rules.yaml)

Fix: #503

2024-11-28 18:11 UTC, zmraul approved these changes, later dismissed

2024-11-28 22:36 UTC, Mehdi-Bendriss requested changes

2024-11-28 22:36 UTC, Mehdi-Bendriss commented on src/alert_rules/prometheus/prometheus_alerts.yaml
> +    expr: sum by (cluster, instance, node) (write:rejected_requests:rate2m) / on (cluster, instance, node) (write:completed_requests:rate2m)
I believe the rate formula is not accurate here. The denominator should be "completed requests + rejected_requests" to have the right rate of failed requests

2024-11-29 15:16 UTC, Mehdi-Bendriss approved these changes

2024-11-29 16:38 UTC, zmraul approved these changes

2024-11-29 18:05 UTC, merged